[package]
name = "rust_starter_project"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# All documentation for crates available on docs.rs

[dependencies]
